# Generated by Django 3.1.7 on 2021-04-03 18:46

from django.db import migrations


def populate_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.bulk_create(
        [
            Group(name="foreman"),
            Group(name="new_employee"),
            Group(name="cottage_worker"),
            Group(name="stationary_worker"),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("syto_api", "0001_squashed_0005_auto_20210329_1040"),
    ]

    operations = [migrations.RunPython(populate_groups)]
