# Generated by Django 3.1.7 on 2021-03-09 19:48

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syto_api", "0002_auto_20210303_1124"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="evidence_number",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
