# Generated by Django 3.1.7 on 2021-04-07 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syto_api", "0002_auto_20210403_1846"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabilityhours",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="syto_api.slot"
            ),
        ),
        migrations.AlterField(
            model_name="availabilityperiod",
            name="end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="availabilityperiod",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="syto_api.slot"
            ),
        ),
        migrations.AlterField(
            model_name="availabilityperiod",
            name="start",
            field=models.DateTimeField(),
        ),
    ]
