# Generated by Django 3.1.7 on 2021-03-10 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syto_api", "0003_auto_20210309_1948"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                ("day", models.DateField(primary_key=True, serialize=False)),
                (
                    "stationary_workers_limit",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "is_open_for_cottage_workers",
                    models.BooleanField(blank=True, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="availabilityhours",
            name="day",
        ),
        migrations.AlterField(
            model_name="availabilityperiod",
            name="end",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="availabilityperiod",
            name="start",
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name="availabilityhours",
            name="slot",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="syto_api.slot",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="availabilityperiod",
            name="slot",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="syto_api.slot",
            ),
            preserve_default=False,
        ),
    ]
