# Generated by Django 3.1.7 on 2021-03-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("syto_api", "0004_auto_20210310_1905"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="availabilityhours",
            options={"verbose_name_plural": "Availability hours"},
        ),
    ]
